# Generated by Django 6.0.8 on 2026-09-30 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('meeting_provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('other', 'Other')], default='zoom', max_length=20)),
                ('meeting_url', models.URLField(max_length=500)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_classes_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'live class',
                'verbose_name_plural': 'live classes',
                'ordering': ('scheduled_start',),
                'indexes': [models.Index(fields=['course', 'scheduled_start'], name='liveclass_course_start_idx')],
            },
        ),
    ]
