# Generated by Django 6.0.8 on 2026-09-22 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('subscription_activated', 'Subscription activated'), ('subscription_expiring', 'Subscription expiring soon'), ('subscription_expired', 'Subscription expired'), ('password_reset', 'Password reset'), ('account_verification', 'Account verification'), ('course_enrolled', 'Course enrollment'), ('quiz_result', 'Quiz result')], db_index=True, max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-app')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
            },
        ),
    ]
