# Generated by Django 6.0.8 on 2026-09-22 11:40

import apps.users.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(blank=True, help_text='Optional contact number in E.164 format where possible.', max_length=20, verbose_name='phone')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], db_index=True, default='student', max_length=20, verbose_name='role')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='bio')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot authenticate but keep their history.')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to Django admin.')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
                'indexes': [models.Index(fields=['email'], name='user_email_idx'), models.Index(fields=['role', 'is_active'], name='user_role_active_idx'), models.Index(fields=['date_joined'], name='user_joined_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['student', 'instructor', 'admin'])), name='user_role_valid')],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
