# Generated by Django 6.0.8 on 2026-09-22 11:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playback_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cloudflare_video_id', models.CharField(db_index=True, help_text='Stream video UID returned by the Cloudflare API.', max_length=64, unique=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('require_signed_urls', models.BooleanField(default=True, help_text='When true the asset is private and every playback needs a signed token.')),
                ('max_playback_seconds', models.PositiveIntegerField(default=0, help_text='Optional rating limit for signed tokens (0 = unlimited).')),
                ('processing_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='video_status_created_idx'), models.Index(fields=['cloudflare_video_id'], name='video_cf_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'ready', 'failed'])), name='video_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('token_fingerprint', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='videos.video')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='playback_user_created_idx'), models.Index(fields=['video', 'created_at'], name='playback_video_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0, help_text='Furthest continuous position reached (seconds).')),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Where to resume playback (seconds).')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='videos.video')),
            ],
            options={
                'verbose_name': 'video progress',
                'verbose_name_plural': 'video progress',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'lesson'], name='progress_user_lesson_idx'), models.Index(fields=['user', 'updated_at'], name='progress_user_recent_idx'), models.Index(fields=['user', 'completed'], name='progress_user_completed_idx'), models.Index(fields=['video', 'completed'], name='progress_video_completed_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'video'), name='unique_progress_per_user_video'), models.CheckConstraint(condition=models.Q(('completion_percentage__gte', 0), ('completion_percentage__lte', 100)), name='progress_percentage_range')],
            },
        ),
    ]
