# Generated by Django 6.0.8 on 2026-09-22 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('quiz_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('quizzes_passed', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(db_index=True, default=0)),
                ('courses_completed', models.PositiveIntegerField(db_index=True, default=0)),
                ('courses_enrolled', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'leaderboard entry',
                'verbose_name_plural': 'leaderboard entries',
                'ordering': ('-total_score', '-lessons_completed', 'user__date_joined'),
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, default='global', max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entries', models.JSONField(default=list, help_text='Top-N rows at capture time.')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
    ]
