# Generated by Django 6.0.8 on 2026-09-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['scope', '-captured_at'], name='snapshot_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-total_score', '-lessons_completed', 'user'], name='lb_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-courses_completed'], name='lb_courses_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['last_activity_at'], name='lb_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0)), name='lb_total_non_negative'),
        ),
    ]
