# Generated by Django 6.0.8 on 2026-09-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'ordering'], name='option_question_order_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'is_correct'], name='option_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'ordering'), name='unique_option_ordering_per_question'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_published'], name='quiz_course_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('pass_percentage__gte', 1), ('pass_percentage__lte', 100)), name='quiz_pass_percentage_range'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'ordering'], name='question_quiz_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'ordering'), name='unique_question_ordering_per_quiz'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-started_at'], name='attempt_user_quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'passed', 'score'], name='attempt_user_score_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-score'], name='attempt_quiz_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('quiz', 'user', 'attempt_number'), name='unique_attempt_number_per_user_quiz'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='attempt_percentage_range'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='answer_attempt_correct_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['question'], name='answer_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
    ]
