# Generated by Django 6.0.8 on 2026-09-22 11:40

import apps.core.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.ImageField(blank=True, help_text='Card/hero image. Videos are never stored on this server.', null=True, upload_to='courses/thumbnails/%Y/%m/', validators=[apps.core.validators.ValidatedImageFile()])),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Display price in INR. Access is granted via subscription plans.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('unlock_rule', models.CharField(choices=[('subscription', 'Subscription'), ('free', 'Free')], default='subscription', help_text='FREE courses are visible to any authenticated student.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Denormalised total; refreshed when lessons change.')),
                ('lesson_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='English', max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Cached from the video row for cheap list rendering.')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=1)),
                ('is_preview', models.BooleanField(default=False, help_text='Preview lessons are watchable without any subscription.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ('ordering', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(db_index=True, default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ('ordering', 'created_at'),
            },
        ),
    ]
