# Generated by Django 6.0.8 on 2026-09-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['instructor', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.OneToOneField(blank=True, help_text='Cloudflare Stream metadata row; the file itself never touches Django.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='videos.video'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='course_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='course_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='course_instructor_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['unlock_rule', 'status'], name='course_unlock_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='course_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'archived'])), name='course_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('unlock_rule__in', ['subscription', 'free'])), name='course_unlock_rule_valid'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'ordering'], name='section_course_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'ordering'), name='unique_section_ordering_per_course'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['section', 'ordering'], name='lesson_section_order_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', 'is_preview'], name='lesson_status_preview_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('section', 'ordering'), name='unique_lesson_ordering_per_section'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('video__isnull', False), ('quiz__isnull', False), _connector='OR'), name='lesson_requires_video_or_quiz'),
        ),
    ]
